name: Build and push Google Drive File Exporter Image

on:
  push:
    tags:
      - 'v*'

env:
  BWS_DOCKERHUB_USERNAME: 298d6b29-803d-4f39-ac32-b16100c595ac
  BWS_DOCKERHUB_TOKEN: 5a41fac5-0528-4cad-9af5-b15f013c4634
  DOCKER_IMAGE_NAME: adnanjaw/google-drive-file-exporter
  TEST_TAG: test
  LATEST_TAG: latest

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Fetch Secrets From BWS
        uses: bitwarden/sm-action@v2.0.0
        with:
          access_token: ${{ secrets.BWS_TOKEN }}
          secrets: |
            ${{ env.BWS_DOCKERHUB_USERNAME }}  > DOCKERHUB_USERNAME
            ${{ env.BWS_DOCKERHUB_TOKEN }} > DOCKERHUB_TOKEN
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ env.DOCKERHUB_TOKEN }}
      -
        name: Build and export to Docker
        uses: docker/build-push-action@v5
        with:
          context: .
          load: true
          tags: '${{ env.DOCKER_IMAGE_NAME }}:${{ env.TEST_TAG }}'
      - name: Test
        run: |
          docker run --rm '${{ env.DOCKER_IMAGE_NAME }}:${{ env.TEST_TAG }}'
      - name: Build and push latest
        if: success()
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: '${{ env.DOCKER_IMAGE_NAME }}:${{ env.LATEST_TAG }}'
      -
        name: Build and push v.x.x
        if: success()
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: '${{ env.DOCKER_IMAGE_NAME }}:${{ github.ref_name }}'
